### PR TITLE
This will allow the device to have more free RAM.

### PR DESCRIPTION
**Pull request by wednesday2024**
If this code is here, this device will be able to handle future Android versions without a problem. I am aware the device already has 4GB of RAM but hear me out, these settings will help with having less RAM usage.

### CODE REVIEW

**Comment by Linux4** [comment]
Are you really sure about this?
Currently I don't see any problems with RAM usage, so this will probably only limit device's multitasking.
Afaik ro.config.low_ram=true is only intended for devices with <= 512MB RAM.

Also I haven't seem some of these props on newer Android versions, could you maybe link me where you got them from?

If future Android versions will have problems with 4GB RAM we can still address it there so I don't see a reason to merge this for now.

**Comment by wednesday2024** [comment]
> Are you really sure about this?
> Currently I don't see any problems with RAM usage, so this will probably only limit device's multitasking.
> Afaik ro.config.low_ram=true is only intended for devices with <= 512MB RAM.
> 
> Also I haven't seem some of these props on newer Android versions, could you maybe link me where you got them from?
> 
> If future Android versions will have problems with 4GB RAM we can still address it there so I don't see a reason to merge this for now.

It works fine on the Samsung Galaxy Note 10.1" wifi 2012 GT-N8010 & GT-N8013. It has 2GB of RAM. It has unofficial builds for LneageOS 16.0.
https://github.com/Ryzen5-3600/android_device_samsung_n8013/blob/lineage-16.0/system.prop
The 4GB RAM isn't a problem at this point and time. But I wouldn't think it would hurt to begin with future proofing it?
If you think enabling low ram is a problem, I can modify my changes to remove that line.

**Comment by wednesday2024** [comment]
Also, to be fair, while I was testing RAM usage on this device. Stock OneUI 2.5 has about 2.5GB used of RAM. LineageOS 17.1 has about 2.3-2.4GB used of RAM.

**Comment by wednesday2024** [comment]
On the Samsung Note 10.1", the RAM usage went from 1GB used to about 300-400MB used.

**Comment by Linux4** [comment]
> > Are you really sure about this?
> > Currently I don't see any problems with RAM usage, so this will probably only limit device's multitasking.
> > Afaik ro.config.low_ram=true is only intended for devices with <= 512MB RAM.
> > Also I haven't seem some of these props on newer Android versions, could you maybe link me where you got them from?
> > If future Android versions will have problems with 4GB RAM we can still address it there so I don't see a reason to merge this for now.
> 
> It works fine on the Samsung Galaxy Note 10.1" wifi 2012 GT-N8010 & GT-N8013. It has 2GB of RAM. It has unofficial builds for LneageOS 16.0.
> https://github.com/Ryzen5-3600/android_device_samsung_n8013/blob/lineage-16.0/system.prop
> The 4GB RAM isn't a problem at this point and time. But I wouldn't think it would hurt to begin with future proofing it?
> If you think enabling low ram is a problem, I can modify my changes to remove that line.

You talk of 'future proofing it' but we'll definitely need modifications to sources for newer android versions anyways so why not keep it like it is for now and apply this when it's *really* going to be needed?

> Also, to be fair, while I was testing RAM usage on this device. Stock OneUI 2.5 has about 2.5GB used of RAM. LineageOS 17.1 has about 2.3-2.4GB used of RAM.

This is absolutely normal, even on my S10 it always uses a bit more than 50% of RAM (it got 8GB RAM and I don't really have many apps installed), I believe this is for caching/buffering stuff and should actually help to improve performance...
Did you actually test the impact of this on multitasking and also general performance?

> On the Samsung Note 10.1", the RAM usage went from 1GB used to about 300-400MB used.

See my comment above.

**Comment by wednesday2024** [comment]
> > > Are you really sure about this?
> > > Currently I don't see any problems with RAM usage, so this will probably only limit device's multitasking.
> > > Afaik ro.config.low_ram=true is only intended for devices with <= 512MB RAM.
> > > Also I haven't seem some of these props on newer Android versions, could you maybe link me where you got them from?
> > > If future Android versions will have problems with 4GB RAM we can still address it there so I don't see a reason to merge this for now.
> > 
> > 
> > It works fine on the Samsung Galaxy Note 10.1" wifi 2012 GT-N8010 & GT-N8013. It has 2GB of RAM. It has unofficial builds for LneageOS 16.0.
> > https://github.com/Ryzen5-3600/android_device_samsung_n8013/blob/lineage-16.0/system.prop
> > The 4GB RAM isn't a problem at this point and time. But I wouldn't think it would hurt to begin with future proofing it?
> > If you think enabling low ram is a problem, I can modify my changes to remove that line.
> 
> You talk of 'future proofing it' but we'll definitely need modifications to sources for newer android versions anyways so why not keep it like it is for now and apply this when it's _really_ going to be needed?
> 
> > Also, to be fair, while I was testing RAM usage on this device. Stock OneUI 2.5 has about 2.5GB used of RAM. LineageOS 17.1 has about 2.3-2.4GB used of RAM.
> 
> This is absolutely normal, even on my S10 it always uses a bit more than 50% of RAM (it got 8GB RAM and I don't really have many apps installed), I believe this is for caching/buffering stuff and should actually help to improve performance...
> Did you actually test the impact of this on multitasking and also general performance?
> 
> > On the Samsung Note 10.1", the RAM usage went from 1GB used to about 300-400MB used.
> 
> See my comment above.

I tested the RAM usage on LOS 17 and stock one ui 2.5 on a brand new install. Nothing running, modified, nor installed.

**Comment by Linux4** [comment]
> > > > Are you really sure about this?
> > > > Currently I don't see any problems with RAM usage, so this will probably only limit device's multitasking.
> > > > Afaik ro.config.low_ram=true is only intended for devices with <= 512MB RAM.
> > > > Also I haven't seem some of these props on newer Android versions, could you maybe link me where you got them from?
> > > > If future Android versions will have problems with 4GB RAM we can still address it there so I don't see a reason to merge this for now.
> > > 
> > > 
> > > It works fine on the Samsung Galaxy Note 10.1" wifi 2012 GT-N8010 & GT-N8013. It has 2GB of RAM. It has unofficial builds for LneageOS 16.0.
> > > https://github.com/Ryzen5-3600/android_device_samsung_n8013/blob/lineage-16.0/system.prop
> > > The 4GB RAM isn't a problem at this point and time. But I wouldn't think it would hurt to begin with future proofing it?
> > > If you think enabling low ram is a problem, I can modify my changes to remove that line.
> > 
> > 
> > You talk of 'future proofing it' but we'll definitely need modifications to sources for newer android versions anyways so why not keep it like it is for now and apply this when it's _really_ going to be needed?
> > > Also, to be fair, while I was testing RAM usage on this device. Stock OneUI 2.5 has about 2.5GB used of RAM. LineageOS 17.1 has about 2.3-2.4GB used of RAM.
> > 
> > 
> > This is absolutely normal, even on my S10 it always uses a bit more than 50% of RAM (it got 8GB RAM and I don't really have many apps installed), I believe this is for caching/buffering stuff and should actually help to improve performance...
> > Did you actually test the impact of this on multitasking and also general performance?
> > > On the Samsung Note 10.1", the RAM usage went from 1GB used to about 300-400MB used.
> > 
> > 
> > See my comment above.
> 
> I tested the RAM usage on LOS 17 and stock one ui 2.5 on a brand new install. Nothing running, modified, nor installed.

Actually I meant if you tested the changes you want to submit with this PR ...

**Comment by wednesday2024** [comment]
> > > > > Are you really sure about this?
> > > > > Currently I don't see any problems with RAM usage, so this will probably only limit device's multitasking.
> > > > > Afaik ro.config.low_ram=true is only intended for devices with <= 512MB RAM.
> > > > > Also I haven't seem some of these props on newer Android versions, could you maybe link me where you got them from?
> > > > > If future Android versions will have problems with 4GB RAM we can still address it there so I don't see a reason to merge this for now.
> > > > 
> > > > 
> > > > It works fine on the Samsung Galaxy Note 10.1" wifi 2012 GT-N8010 & GT-N8013. It has 2GB of RAM. It has unofficial builds for LneageOS 16.0.
> > > > https://github.com/Ryzen5-3600/android_device_samsung_n8013/blob/lineage-16.0/system.prop
> > > > The 4GB RAM isn't a problem at this point and time. But I wouldn't think it would hurt to begin with future proofing it?
> > > > If you think enabling low ram is a problem, I can modify my changes to remove that line.
> > > 
> > > 
> > > You talk of 'future proofing it' but we'll definitely need modifications to sources for newer android versions anyways so why not keep it like it is for now and apply this when it's _really_ going to be needed?
> > > > Also, to be fair, while I was testing RAM usage on this device. Stock OneUI 2.5 has about 2.5GB used of RAM. LineageOS 17.1 has about 2.3-2.4GB used of RAM.
> > > 
> > > 
> > > This is absolutely normal, even on my S10 it always uses a bit more than 50% of RAM (it got 8GB RAM and I don't really have many apps installed), I believe this is for caching/buffering stuff and should actually help to improve performance...
> > > Did you actually test the impact of this on multitasking and also general performance?
> > > > On the Samsung Note 10.1", the RAM usage went from 1GB used to about 300-400MB used.
> > > 
> > > 
> > > See my comment above.
> > 
> > 
> > I tested the RAM usage on LOS 17 and stock one ui 2.5 on a brand new install. Nothing running, modified, nor installed.
> 
> Actually I meant if you tested the changes you want to submit with this PR ...

May I ask, what is PR?

**Comment by Linux4** [comment]
> > > > > > Are you really sure about this?
> > > > > > Currently I don't see any problems with RAM usage, so this will probably only limit device's multitasking.
> > > > > > Afaik ro.config.low_ram=true is only intended for devices with <= 512MB RAM.
> > > > > > Also I haven't seem some of these props on newer Android versions, could you maybe link me where you got them from?
> > > > > > If future Android versions will have problems with 4GB RAM we can still address it there so I don't see a reason to merge this for now.
> > > > > 
> > > > > 
> > > > > It works fine on the Samsung Galaxy Note 10.1" wifi 2012 GT-N8010 & GT-N8013. It has 2GB of RAM. It has unofficial builds for LneageOS 16.0.
> > > > > https://github.com/Ryzen5-3600/android_device_samsung_n8013/blob/lineage-16.0/system.prop
> > > > > The 4GB RAM isn't a problem at this point and time. But I wouldn't think it would hurt to begin with future proofing it?
> > > > > If you think enabling low ram is a problem, I can modify my changes to remove that line.
> > > > 
> > > > 
> > > > You talk of 'future proofing it' but we'll definitely need modifications to sources for newer android versions anyways so why not keep it like it is for now and apply this when it's _really_ going to be needed?
> > > > > Also, to be fair, while I was testing RAM usage on this device. Stock OneUI 2.5 has about 2.5GB used of RAM. LineageOS 17.1 has about 2.3-2.4GB used of RAM.
> > > > 
> > > > 
> > > > This is absolutely normal, even on my S10 it always uses a bit more than 50% of RAM (it got 8GB RAM and I don't really have many apps installed), I believe this is for caching/buffering stuff and should actually help to improve performance...
> > > > Did you actually test the impact of this on multitasking and also general performance?
> > > > > On the Samsung Note 10.1", the RAM usage went from 1GB used to about 300-400MB used.
> > > > 
> > > > 
> > > > See my comment above.
> > > 
> > > 
> > > I tested the RAM usage on LOS 17 and stock one ui 2.5 on a brand new install. Nothing running, modified, nor installed.
> > 
> > 
> > Actually I meant if you tested the changes you want to submit with this PR ...
> 
> May I ask, what is PR?

Pull request

**Comment by wednesday2024** [comment]
> > > > > > > Are you really sure about this?
> > > > > > > Currently I don't see any problems with RAM usage, so this will probably only limit device's multitasking.
> > > > > > > Afaik ro.config.low_ram=true is only intended for devices with <= 512MB RAM.
> > > > > > > Also I haven't seem some of these props on newer Android versions, could you maybe link me where you got them from?
> > > > > > > If future Android versions will have problems with 4GB RAM we can still address it there so I don't see a reason to merge this for now.
> > > > > > 
> > > > > > 
> > > > > > It works fine on the Samsung Galaxy Note 10.1" wifi 2012 GT-N8010 & GT-N8013. It has 2GB of RAM. It has unofficial builds for LneageOS 16.0.
> > > > > > https://github.com/Ryzen5-3600/android_device_samsung_n8013/blob/lineage-16.0/system.prop
> > > > > > The 4GB RAM isn't a problem at this point and time. But I wouldn't think it would hurt to begin with future proofing it?
> > > > > > If you think enabling low ram is a problem, I can modify my changes to remove that line.
> > > > > 
> > > > > 
> > > > > You talk of 'future proofing it' but we'll definitely need modifications to sources for newer android versions anyways so why not keep it like it is for now and apply this when it's _really_ going to be needed?
> > > > > > Also, to be fair, while I was testing RAM usage on this device. Stock OneUI 2.5 has about 2.5GB used of RAM. LineageOS 17.1 has about 2.3-2.4GB used of RAM.
> > > > > 
> > > > > 
> > > > > This is absolutely normal, even on my S10 it always uses a bit more than 50% of RAM (it got 8GB RAM and I don't really have many apps installed), I believe this is for caching/buffering stuff and should actually help to improve performance...
> > > > > Did you actually test the impact of this on multitasking and also general performance?
> > > > > > On the Samsung Note 10.1", the RAM usage went from 1GB used to about 300-400MB used.
> > > > > 
> > > > > 
> > > > > See my comment above.
> > > > 
> > > > 
> > > > I tested the RAM usage on LOS 17 and stock one ui 2.5 on a brand new install. Nothing running, modified, nor installed.
> > > 
> > > 
> > > Actually I meant if you tested the changes you want to submit with this PR ...
> > 
> > 
> > May I ask, what is PR?
> 
> Pull request

That’s what I thought. I currently have my changes compiling at the moment. I will test it later tonight when it is fully completed with compiling. But like I said, when I tested it on the Samsung note 10.1, I had no issues with having these changes. It actually performed a lot better.

**Comment by wednesday2024** [comment]
> > > > > > > Are you really sure about this?
> > > > > > > Currently I don't see any problems with RAM usage, so this will probably only limit device's multitasking.
> > > > > > > Afaik ro.config.low_ram=true is only intended for devices with <= 512MB RAM.
> > > > > > > Also I haven't seem some of these props on newer Android versions, could you maybe link me where you got them from?
> > > > > > > If future Android versions will have problems with 4GB RAM we can still address it there so I don't see a reason to merge this for now.
> > > > > > 
> > > > > > 
> > > > > > It works fine on the Samsung Galaxy Note 10.1" wifi 2012 GT-N8010 & GT-N8013. It has 2GB of RAM. It has unofficial builds for LneageOS 16.0.
> > > > > > https://github.com/Ryzen5-3600/android_device_samsung_n8013/blob/lineage-16.0/system.prop
> > > > > > The 4GB RAM isn't a problem at this point and time. But I wouldn't think it would hurt to begin with future proofing it?
> > > > > > If you think enabling low ram is a problem, I can modify my changes to remove that line.
> > > > > 
> > > > > 
> > > > > You talk of 'future proofing it' but we'll definitely need modifications to sources for newer android versions anyways so why not keep it like it is for now and apply this when it's _really_ going to be needed?
> > > > > > Also, to be fair, while I was testing RAM usage on this device. Stock OneUI 2.5 has about 2.5GB used of RAM. LineageOS 17.1 has about 2.3-2.4GB used of RAM.
> > > > > 
> > > > > 
> > > > > This is absolutely normal, even on my S10 it always uses a bit more than 50% of RAM (it got 8GB RAM and I don't really have many apps installed), I believe this is for caching/buffering stuff and should actually help to improve performance...
> > > > > Did you actually test the impact of this on multitasking and also general performance?
> > > > > > On the Samsung Note 10.1", the RAM usage went from 1GB used to about 300-400MB used.
> > > > > 
> > > > > 
> > > > > See my comment above.
> > > > 
> > > > 
> > > > I tested the RAM usage on LOS 17 and stock one ui 2.5 on a brand new install. Nothing running, modified, nor installed.
> > > 
> > > 
> > > Actually I meant if you tested the changes you want to submit with this PR ...
> > 
> > 
> > May I ask, what is PR?
> 
> Pull request

Here is my test build. You can try it out if you would like: https://github.com/Ryzen5-3600/android/releases/tag/gta4xlwifi-12-2020

**Comment by Linux4** [comment]
I just tested these props, and I won't merge this, sorry
E.g this disables splitscreen or freeform windows (I already expected that) and I don't really see much performance gain.
We would just pay a too high price for this in my opinion.
I told you it seems to be normal anyways that system targets to fill ~50% of RAM.

**Pull request closed without merging**
